//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhetos.DatabaseGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql_MsSql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql_MsSql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rhetos.DatabaseGenerator.Sql.MsSql", typeof(Sql_MsSql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Rhetos.AppliedConcept WHERE ID={0}.
        /// </summary>
        internal static string ConceptApplicationRepository_Delete {
            get {
                return ResourceManager.GetString("ConceptApplicationRepository_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Rhetos.AppliedConceptDependsOn;
        ///DELETE FROM Rhetos.AppliedConcept;.
        /// </summary>
        internal static string ConceptApplicationRepository_DeleteAll {
            get {
                return ResourceManager.GetString("ConceptApplicationRepository_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Rhetos.AppliedConceptDependsOn WHERE DependentID = {0} AND DependsOnID = {1}.
        /// </summary>
        internal static string ConceptApplicationRepository_DeleteDependency {
            get {
                return ResourceManager.GetString("ConceptApplicationRepository_DeleteDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Rhetos.AppliedConcept (ID, InfoType, ConceptInfoKey, ImplementationType, SerializedInfo, CreateQuery, RemoveQuery, ConceptImplementationVersion)
        ///VALUES ({0}, N{1}, N{2}, N{3}, N{4}, N{5}, N{6}, N{7}).
        /// </summary>
        internal static string ConceptApplicationRepository_Insert {
            get {
                return ResourceManager.GetString("ConceptApplicationRepository_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Rhetos.AppliedConceptDependsOn (DependentID, DependsOnID) VALUES ({0}, {1}).
        /// </summary>
        internal static string ConceptApplicationRepository_InsertDependency {
            get {
                return ResourceManager.GetString("ConceptApplicationRepository_InsertDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Rhetos.AppliedConcept
        ///SET
        ///  InfoType = N{1},
        ///  ConceptInfoKey = N{2},
        ///  ImplementationType = N{3},
        ///  SerializedInfo = N{4},
        ///  CreateQuery = N{5},
        ///  RemoveQuery = N{6},
        ///  ConceptImplementationVersion = N{7}
        ///WHERE ID = {0}.
        /// </summary>
        internal static string ConceptApplicationRepository_Update {
            get {
                return ResourceManager.GetString("ConceptApplicationRepository_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseGenerator_CommitAfterDDL {
            get {
                return ResourceManager.GetString("DatabaseGenerator_CommitAfterDDL", resourceCulture);
            }
        }
    }
}
