//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhetos.DatabaseGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql_Oracle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql_Oracle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rhetos.DatabaseGenerator.Sql.Oracle", typeof(Sql_Oracle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN
        ///  DELETE FROM Rhetos.AppliedConcept WHERE ID={0};
        ///  COMMIT;
        ///END;.
        /// </summary>
        internal static string ConceptApplicationRepository_Delete {
            get {
                return ResourceManager.GetString("ConceptApplicationRepository_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN
        ///DELETE FROM Rhetos.AppliedConceptDependsOn;
        ///DELETE FROM Rhetos.AppliedConcept;
        ///END;.
        /// </summary>
        internal static string ConceptApplicationRepository_DeleteAll {
            get {
                return ResourceManager.GetString("ConceptApplicationRepository_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Rhetos.AppliedConceptDependsOn WHERE DependentID = {0} AND DependsOnID = {1}.
        /// </summary>
        internal static string ConceptApplicationRepository_DeleteDependency {
            get {
                return ResourceManager.GetString("ConceptApplicationRepository_DeleteDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE
        ///	InfoType NCLOB;
        ///	ConceptInfoKey NCLOB;
        ///	ImplementationType NCLOB;
        ///	SerializedInfo NCLOB;
        ///	CreateQuery NCLOB;
        ///	RemoveQuery NCLOB;
        ///BEGIN
        ///	InfoType := N{1};
        ///	ConceptInfoKey := N{2};
        ///	ImplementationType := N{3};
        ///	SerializedInfo := N{4};
        ///	CreateQuery := N{5};
        ///	RemoveQuery := N{6};
        ///	
        ///	INSERT INTO Rhetos.AppliedConcept (ID, InfoType, ConceptInfoKey, ImplementationType, SerializedInfo, CreateQuery, RemoveQuery, ConceptImplementationVersion)
        ///	VALUES ({0}, InfoType, ConceptInfoKey, Implementa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConceptApplicationRepository_Insert {
            get {
                return ResourceManager.GetString("ConceptApplicationRepository_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Rhetos.AppliedConceptDependsOn (DependentID, DependsOnID) VALUES ({0}, {1}).
        /// </summary>
        internal static string ConceptApplicationRepository_InsertDependency {
            get {
                return ResourceManager.GetString("ConceptApplicationRepository_InsertDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE
        ///	vInfoType NCLOB;
        ///	vConceptInfoKey NCLOB;
        ///	vImplementationType NCLOB;
        ///	vSerializedInfo NCLOB;
        ///	vCreateQuery NCLOB;
        ///	vRemoveQuery NCLOB;
        ///BEGIN
        ///	vInfoType := N{1};
        ///	vConceptInfoKey := N{2};
        ///	vImplementationType := N{3};
        ///	vSerializedInfo := N{4};
        ///	vCreateQuery := N{5};
        ///	vRemoveQuery := N{6};
        ///	
        ///	UPDATE Rhetos.AppliedConcept
        ///	SET
        ///    InfoType = vInfoType,
        ///    ConceptInfoKey = vConceptInfoKey,
        ///    ImplementationType = vImplementationType,
        ///    SerializedInfo = vSerializedInfo,
        ///    Crea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConceptApplicationRepository_Update {
            get {
                return ResourceManager.GetString("ConceptApplicationRepository_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMIT.
        /// </summary>
        internal static string DatabaseGenerator_CommitAfterDDL {
            get {
                return ResourceManager.GetString("DatabaseGenerator_CommitAfterDDL", resourceCulture);
            }
        }
    }
}
