//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhetos.DatabaseGenerator.DefaultConcepts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql_Oracle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql_Oracle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rhetos.DatabaseGenerator.DefaultConcepts.Sql.Oracle", typeof(Sql_Oracle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOB.
        /// </summary>
        internal static string BinaryPropertyDatabaseDefinition_DataType {
            get {
                return ResourceManager.GetString("BinaryPropertyDatabaseDefinition_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMBER(3).
        /// </summary>
        internal static string BoolPropertyDatabaseDefinition_DataType {
            get {
                return ResourceManager.GetString("BoolPropertyDatabaseDefinition_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_{0}_ID.
        /// </summary>
        internal static string DataStructureExtendsDatabaseDefinition_ConstraintName {
            get {
                return ResourceManager.GetString("DataStructureExtendsDatabaseDefinition_ConstraintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE {0} ADD CONSTRAINT {1} FOREIGN KEY (ID) REFERENCES {2} (ID) ON DELETE CASCADE {3}.
        /// </summary>
        internal static string DataStructureExtendsDatabaseDefinition_Create {
            get {
                return ResourceManager.GetString("DataStructureExtendsDatabaseDefinition_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE {0} DROP CONSTRAINT {1}.
        /// </summary>
        internal static string DataStructureExtendsDatabaseDefinition_Remove {
            get {
                return ResourceManager.GetString("DataStructureExtendsDatabaseDefinition_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        internal static string DatePropertyDatabaseDefinition_DataType {
            get {
                return ResourceManager.GetString("DatePropertyDatabaseDefinition_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        internal static string DateTimePropertyDatabaseDefinition_DataType {
            get {
                return ResourceManager.GetString("DateTimePropertyDatabaseDefinition_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMBER(28,10).
        /// </summary>
        internal static string DecimalPropertyDatabaseDefinition_DataType {
            get {
                return ResourceManager.GetString("DecimalPropertyDatabaseDefinition_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE {0}.{1} (ID RAW(16) DEFAULT SYS_GUID() NOT NULL
        ///CONSTRAINT {2} PRIMARY KEY).
        /// </summary>
        internal static string EntityDatabaseDefinition_Create {
            get {
                return ResourceManager.GetString("EntityDatabaseDefinition_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DF_{1}_ID.
        /// </summary>
        internal static string EntityDatabaseDefinition_DefaultConstraintName {
            get {
                return ResourceManager.GetString("EntityDatabaseDefinition_DefaultConstraintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PK_{1}.
        /// </summary>
        internal static string EntityDatabaseDefinition_PrimaryKeyConstraintName {
            get {
                return ResourceManager.GetString("EntityDatabaseDefinition_PrimaryKeyConstraintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE {0}.{1}.
        /// </summary>
        internal static string EntityDatabaseDefinition_Remove {
            get {
                return ResourceManager.GetString("EntityDatabaseDefinition_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER {0}.{2}
        ///AFTER INSERT ON {0}.{1}
        ///FOR EACH ROW 
        ///BEGIN
        ///	INSERT INTO Common.Log
        ///    (
        ///        Action,
        ///        TableName,
        ///        ItemId,
        ///        Description
        ///    )
        ///	VALUES
        ///	(
        ///		&apos;Insert&apos;,
        ///		&apos;{0}.{1}&apos;,
        ///		:NEW.ID,
        ///		&apos;&apos;
        ///	);
        ///END;
        ///{5}
        ///CREATE TRIGGER {0}.{3}
        ///AFTER UPDATE ON {0}.{1}
        ///FOR EACH ROW 
        ///BEGIN
        ///	INSERT INTO Common.Log
        ///    (
        ///        Action,
        ///        TableName,
        ///        ItemId,
        ///        Description
        ///    )
        ///	VALUES
        ///	(
        ///		&apos;Update&apos;,
        ///		&apos;{0}.{1}&apos;,
        ///		:NEW.ID,
        ///		N&apos;&lt;PREVIOUS&apos;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityLoggingDefinition_Create {
            get {
                return ResourceManager.GetString("EntityLoggingDefinition_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN
        ///  EXECUTE IMMEDIATE(&apos;DROP TRIGGER {0}.{1}&apos;);
        ///  EXECUTE IMMEDIATE(&apos;DROP TRIGGER {0}.{2}&apos;);
        ///  EXECUTE IMMEDIATE(&apos;DROP TRIGGER {0}.{3}&apos;);
        ///END;.
        /// </summary>
        internal static string EntityLoggingDefinition_Remove {
            get {
                return ResourceManager.GetString("EntityLoggingDefinition_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogDelete_{1}.
        /// </summary>
        internal static string EntityLoggingDefinition_TriggerNameDelete {
            get {
                return ResourceManager.GetString("EntityLoggingDefinition_TriggerNameDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogInsert_{1}.
        /// </summary>
        internal static string EntityLoggingDefinition_TriggerNameInsert {
            get {
                return ResourceManager.GetString("EntityLoggingDefinition_TriggerNameInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogUpdate_{1}.
        /// </summary>
        internal static string EntityLoggingDefinition_TriggerNameUpdate {
            get {
                return ResourceManager.GetString("EntityLoggingDefinition_TriggerNameUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAW(16).
        /// </summary>
        internal static string GuidPropertyDatabaseDefinition_DataType {
            get {
                return ResourceManager.GetString("GuidPropertyDatabaseDefinition_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMBER(10).
        /// </summary>
        internal static string IntegerPropertyDatabaseDefinition_DataType {
            get {
                return ResourceManager.GetString("IntegerPropertyDatabaseDefinition_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW {0}.{1}
        ///AS
        ///SELECT
        ///  source.ID{7}
        ///FROM
        ///  {3} source
        ///{8}
        ///
        ///{2}
        ///
        ///CREATE TRIGGER {0}.{4}
        ///INSTEAD OF INSERT ON {0}.{1}
        ///BEGIN
        ///  INSERT INTO
        ///    {3} (ID{9})
        ///  SELECT
        ///    :NEW.ID{10}
        ///  FROM
        ///    dual;
        ///END;
        ///
        ///{2}
        ///
        ///CREATE TRIGGER {0}.{5}
        ///INSTEAD OF UPDATE ON {0}.{1}
        ///BEGIN
        ///  UPDATE
        ///    {3}
        ///  SET
        ///    ID = :NEW.ID{11}
        ///  WHERE
        ///    ID = :OLD.ID;
        ///END;
        ///
        ///{2}
        ///
        ///CREATE TRIGGER {0}.{6}
        ///INSTEAD OF DELETE ON {0}.{1}
        ///BEGIN
        ///  DELETE FROM {3} WHERE ID = :OLD.ID;
        ///END;
        ///
        ///{12}.
        /// </summary>
        internal static string LegacyEntityWithAutoCreatedViewDatabaseDefinition_Create {
            get {
                return ResourceManager.GetString("LegacyEntityWithAutoCreatedViewDatabaseDefinition_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LegacyDelete_{0}.
        /// </summary>
        internal static string LegacyEntityWithAutoCreatedViewDatabaseDefinition_DeleteTriggerName {
            get {
                return ResourceManager.GetString("LegacyEntityWithAutoCreatedViewDatabaseDefinition_DeleteTriggerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LegacyInsert_{0}.
        /// </summary>
        internal static string LegacyEntityWithAutoCreatedViewDatabaseDefinition_InsertTriggerName {
            get {
                return ResourceManager.GetString("LegacyEntityWithAutoCreatedViewDatabaseDefinition_InsertTriggerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN
        ///  EXECUTE IMMEDIATE(&apos;DROP TRIGGER {0}.{4}&apos;);
        ///  EXECUTE IMMEDIATE(&apos;DROP TRIGGER {0}.{3}&apos;);
        ///  EXECUTE IMMEDIATE(&apos;DROP TRIGGER {0}.{2}&apos;);
        ///  EXECUTE IMMEDIATE(&apos;DROP VIEW {0}.{1}&apos;);
        ///END;.
        /// </summary>
        internal static string LegacyEntityWithAutoCreatedViewDatabaseDefinition_Remove {
            get {
                return ResourceManager.GetString("LegacyEntityWithAutoCreatedViewDatabaseDefinition_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LegacyUpdate_{0}.
        /// </summary>
        internal static string LegacyEntityWithAutoCreatedViewDatabaseDefinition_UpdateTriggerName {
            get {
                return ResourceManager.GetString("LegacyEntityWithAutoCreatedViewDatabaseDefinition_UpdateTriggerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,
        ///  source.{1} AS {0}.
        /// </summary>
        internal static string LegacyPropertyReadOnlyDatabaseDefinition_ViewSelect {
            get {
                return ResourceManager.GetString("LegacyPropertyReadOnlyDatabaseDefinition_ViewSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1} = source.{2}.
        /// </summary>
        internal static string LegacyPropertyReferenceDatabaseDefinition_ExtendFromJoin {
            get {
                return ResourceManager.GetString("LegacyPropertyReferenceDatabaseDefinition_ExtendFromJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*unused*/.
        /// </summary>
        internal static string LegacyPropertyReferenceDatabaseDefinition_ExtendTriggerFrom {
            get {
                return ResourceManager.GetString("LegacyPropertyReferenceDatabaseDefinition_ExtendTriggerFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0}.
        /// </summary>
        internal static string LegacyPropertyReferenceDatabaseDefinition_ExtendTriggerInsert {
            get {
                return ResourceManager.GetString("LegacyPropertyReferenceDatabaseDefinition_ExtendTriggerInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,
        ///    (SELECT {2} FROM {3} WHERE ID = :NEW.{4}ID) AS {0}.
        /// </summary>
        internal static string LegacyPropertyReferenceDatabaseDefinition_ExtendTriggerSelectForInsert {
            get {
                return ResourceManager.GetString("LegacyPropertyReferenceDatabaseDefinition_ExtendTriggerSelectForInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,
        ///    {0} = (SELECT {2} FROM {3} WHERE ID = :NEW.{4}ID).
        /// </summary>
        internal static string LegacyPropertyReferenceDatabaseDefinition_ExtendTriggerSelectForUpdate {
            get {
                return ResourceManager.GetString("LegacyPropertyReferenceDatabaseDefinition_ExtendTriggerSelectForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   LEFT JOIN {0} {1} ON {2}
        ///.
        /// </summary>
        internal static string LegacyPropertyReferenceDatabaseDefinition_ExtendViewFrom {
            get {
                return ResourceManager.GetString("LegacyPropertyReferenceDatabaseDefinition_ExtendViewFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,
        ///  {1}.ID AS {0}ID.
        /// </summary>
        internal static string LegacyPropertyReferenceDatabaseDefinition_ExtendViewSelect {
            get {
                return ResourceManager.GetString("LegacyPropertyReferenceDatabaseDefinition_ExtendViewSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0}.
        /// </summary>
        internal static string LegacyPropertySimpleDatabaseDefinition_ExtendTriggerInsert {
            get {
                return ResourceManager.GetString("LegacyPropertySimpleDatabaseDefinition_ExtendTriggerInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,
        ///    :NEW.{1} AS {0}.
        /// </summary>
        internal static string LegacyPropertySimpleDatabaseDefinition_ExtendTriggerSelectForInsert {
            get {
                return ResourceManager.GetString("LegacyPropertySimpleDatabaseDefinition_ExtendTriggerSelectForInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,
        ///    {0} = :NEW.{1}.
        /// </summary>
        internal static string LegacyPropertySimpleDatabaseDefinition_ExtendTriggerSelectForUpdate {
            get {
                return ResourceManager.GetString("LegacyPropertySimpleDatabaseDefinition_ExtendTriggerSelectForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,
        ///  source.{1} AS {0}.
        /// </summary>
        internal static string LegacyPropertySimpleDatabaseDefinition_ExtendViewSelect {
            get {
                return ResourceManager.GetString("LegacyPropertySimpleDatabaseDefinition_ExtendViewSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCLOB.
        /// </summary>
        internal static string LongStringPropertyDatabaseDefinition_DataType {
            get {
                return ResourceManager.GetString("LongStringPropertyDatabaseDefinition_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN
        ///  EXECUTE IMMEDIATE (&apos;CREATE USER {0} IDENTIFIED BY null
        ///    DEFAULT TABLESPACE &quot;USERS&quot;
        ///    TEMPORARY TABLESPACE &quot;TEMP&quot;
        ///    ACCOUNT LOCK&apos;);
        ///  EXECUTE IMMEDIATE (&apos;ALTER USER {0} QUOTA UNLIMITED ON USERS&apos;);
        ///  EXECUTE IMMEDIATE (&apos;GRANT UPDATE ANY TABLE TO {0}&apos;);
        ///  EXECUTE IMMEDIATE (&apos;GRANT SELECT ANY TABLE TO {0}&apos;);
        ///  EXECUTE IMMEDIATE (&apos;GRANT INSERT ANY TABLE TO {0}&apos;);
        ///  EXECUTE IMMEDIATE (&apos;GRANT EXECUTE ANY PROCEDURE TO {0}&apos;);
        ///  EXECUTE IMMEDIATE (&apos;GRANT DELETE ANY TABLE TO {0}&apos;);
        ///END;.
        /// </summary>
        internal static string ModuleDatabaseDefinition_Create {
            get {
                return ResourceManager.GetString("ModuleDatabaseDefinition_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP USER {0}.
        /// </summary>
        internal static string ModuleDatabaseDefinition_Remove {
            get {
                return ResourceManager.GetString("ModuleDatabaseDefinition_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMBER(19,4).
        /// </summary>
        internal static string MoneyPropertyDatabaseDefinition_DataType {
            get {
                return ResourceManager.GetString("MoneyPropertyDatabaseDefinition_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE {0}.{1} ADD {2} {3} {4} {5} {6}.
        /// </summary>
        internal static string PropertyDatabaseDefinition_AddColumn {
            get {
                return ResourceManager.GetString("PropertyDatabaseDefinition_AddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE {0}.{1} DROP COLUMN {2}.
        /// </summary>
        internal static string PropertyDatabaseDefinition_RemoveColumn {
            get {
                return ResourceManager.GetString("PropertyDatabaseDefinition_RemoveColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to || CASE WHEN :NEW.{0} &lt;&gt; :OLD.{0}
        ///                    OR :NEW.{0} IS NULL AND :OLD.{0} IS NOT NULL
        ///                    OR :NEW.{0} IS NOT NULL AND :OLD.{0} IS NULL
        ///					THEN N&apos; {0}=&quot;&apos; || REPLACE(REPLACE(REPLACE(REPLACE({1}, &apos;&amp;&apos;, &apos;&amp;amp;&apos;), &apos;&lt;&apos;, &apos;&amp;lt;&apos;), &apos;&gt;&apos;, &apos;&amp;gt;&apos;), &apos;&quot;&apos;, &apos;&amp;quot;&apos;) || N&apos;&quot;&apos;
        ///					ELSE N&apos;&apos; END
        ///			.
        /// </summary>
        internal static string PropertyLoggingDefinition_GenericPropertyLogging {
            get {
                return ResourceManager.GetString("PropertyLoggingDefinition_GenericPropertyLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :OLD.{0}.
        /// </summary>
        internal static string PropertyLoggingDefinition_TextValue {
            get {
                return ResourceManager.GetString("PropertyLoggingDefinition_TextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTL_RAW.CAST_TO_VARCHAR2(:OLD.{0}).
        /// </summary>
        internal static string PropertyLoggingDefinition_TextValue_Binary {
            get {
                return ResourceManager.GetString("PropertyLoggingDefinition_TextValue_Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO_CHAR(:OLD.{0}, &apos;YYYY-MM-DD&quot;T&quot;HH24:MI:SS&apos;).
        /// </summary>
        internal static string PropertyLoggingDefinition_TextValue_Date {
            get {
                return ResourceManager.GetString("PropertyLoggingDefinition_TextValue_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO_CHAR(:OLD.{0}, &apos;YYYY-MM-DD&quot;T&quot;HH24:MI:SS&apos;).
        /// </summary>
        internal static string PropertyLoggingDefinition_TextValue_DateTime {
            get {
                return ResourceManager.GetString("PropertyLoggingDefinition_TextValue_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ON DELETE CASCADE .
        /// </summary>
        internal static string ReferenceCascadeDeleteDatabaseDefinition_ExtendForeignKey {
            get {
                return ResourceManager.GetString("ReferenceCascadeDeleteDatabaseDefinition_ExtendForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_{0}_{2}ID.
        /// </summary>
        internal static string ReferencePropertyConstraintDatabaseDefinition_ConstraintName {
            get {
                return ResourceManager.GetString("ReferencePropertyConstraintDatabaseDefinition_ConstraintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE {0} ADD CONSTRAINT {1} FOREIGN KEY ({2}) REFERENCES {3} (ID) {4}.
        /// </summary>
        internal static string ReferencePropertyConstraintDatabaseDefinition_Create {
            get {
                return ResourceManager.GetString("ReferencePropertyConstraintDatabaseDefinition_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE {0} DROP CONSTRAINT {1}.
        /// </summary>
        internal static string ReferencePropertyConstraintDatabaseDefinition_Remove {
            get {
                return ResourceManager.GetString("ReferencePropertyConstraintDatabaseDefinition_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAW(16).
        /// </summary>
        internal static string ReferencePropertyDatabaseDefinition_DataType {
            get {
                return ResourceManager.GetString("ReferencePropertyDatabaseDefinition_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVARCHAR2({0}).
        /// </summary>
        internal static string ShortStringPropertyDatabaseDefinition_DataType {
            get {
                return ResourceManager.GetString("ShortStringPropertyDatabaseDefinition_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DF_{0}_{1}.
        /// </summary>
        internal static string SqlDefaultPropertyDatabaseDefinition_ConstraintName {
            get {
                return ResourceManager.GetString("SqlDefaultPropertyDatabaseDefinition_ConstraintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE {0}.{1} MODIFY {2} DEFAULT {4}.
        /// </summary>
        internal static string SqlDefaultPropertyDatabaseDefinition_Create {
            get {
                return ResourceManager.GetString("SqlDefaultPropertyDatabaseDefinition_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE {0}.{1} MODIFY {2} DEFAULT NULL.
        /// </summary>
        internal static string SqlDefaultPropertyDatabaseDefinition_Remove {
            get {
                return ResourceManager.GetString("SqlDefaultPropertyDatabaseDefinition_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IX{0}{1}.
        /// </summary>
        internal static string SqlIndex2DatabaseDefinition_ConstraintName {
            get {
                return ResourceManager.GetString("SqlIndex2DatabaseDefinition_ConstraintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IX{0}{1}.
        /// </summary>
        internal static string SqlIndex3DatabaseDefinition_ConstraintName {
            get {
                return ResourceManager.GetString("SqlIndex3DatabaseDefinition_ConstraintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IX{0}{1}.
        /// </summary>
        internal static string SqlIndexDatabaseDefinition_ConstraintName {
            get {
                return ResourceManager.GetString("SqlIndexDatabaseDefinition_ConstraintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IX{0}{1}.
        /// </summary>
        internal static string SqlIndexMultipleDatabaseDefinition_ConstraintName {
            get {
                return ResourceManager.GetString("SqlIndexMultipleDatabaseDefinition_ConstraintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE {4} INDEX {1}.{0} ON {1}.{2} ({3}) {5}.
        /// </summary>
        internal static string SqlIndexMultipleDatabaseDefinition_Create {
            get {
                return ResourceManager.GetString("SqlIndexMultipleDatabaseDefinition_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP INDEX {0}.{2}.
        /// </summary>
        internal static string SqlIndexMultipleDatabaseDefinition_Remove {
            get {
                return ResourceManager.GetString("SqlIndexMultipleDatabaseDefinition_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NLSSORT({0}, &apos;NLS_SORT={1}&apos;).
        /// </summary>
        internal static string SqlIndexMultiplePropertyDatabaseDefinition_National_ShortStringPropertyInfo {
            get {
                return ResourceManager.GetString("SqlIndexMultiplePropertyDatabaseDefinition_National_ShortStringPropertyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE {0}.{1}
        ///{2} AS
        ///{3}.
        /// </summary>
        internal static string SqlProcedureDatabaseDefinition_Create {
            get {
                return ResourceManager.GetString("SqlProcedureDatabaseDefinition_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PROCEDURE {0}.{1}.
        /// </summary>
        internal static string SqlProcedureDatabaseDefinition_Remove {
            get {
                return ResourceManager.GetString("SqlProcedureDatabaseDefinition_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW {0}.{1}
        ///AS
        ///{2}.
        /// </summary>
        internal static string SqlQueryableDatabaseDefinition_Create {
            get {
                return ResourceManager.GetString("SqlQueryableDatabaseDefinition_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP VIEW {0}.{1}.
        /// </summary>
        internal static string SqlQueryableDatabaseDefinition_Remove {
            get {
                return ResourceManager.GetString("SqlQueryableDatabaseDefinition_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIQUE .
        /// </summary>
        internal static string SqlUniqueMultipleDatabaseDefinition_ExtendOption1 {
            get {
                return ResourceManager.GetString("SqlUniqueMultipleDatabaseDefinition_ExtendOption1", resourceCulture);
            }
        }
    }
}
